topic:
  name: ALBUMS
  partitions: 1
  rf: 3
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - 192.168.137.100:9092, 192.168.137.101:9092, 192.168.137.103:9092
    properties:
      schema.registry.url: http://192.168.137.103:8081
    producer:
      bootstrap-servers:
        - 192.168.137.100:9092, 192.168.137.101:9092, 192.168.137.103:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: 1
      batch-size: 32000
      client-id: otel_demo_client
      retries: 2147483647
      properties:
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
  template:
      default-topic:
logging:
  level:
    root: info